// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyOSuVm5qJs5fnIQku4L4UZupD3DfIf64',
    appId: '1:1014162331467:android:f50a64d2bb06645a7ebace',
    messagingSenderId: '1014162331467',
    projectId: 'naberdostum-3db34',
    storageBucket: 'naberdostum-3db34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAQt9ELuyOq-vSIft7eN2gzjsgFwBvAAE',
    appId: '1:1014162331467:ios:f7f5f94f58781dec7ebace',
    messagingSenderId: '1014162331467',
    projectId: 'naberdostum-3db34',
    storageBucket: 'naberdostum-3db34.appspot.com',
    androidClientId: '1014162331467-2ooaioqgujru6fimnqo7o2ee7nqgi7au.apps.googleusercontent.com',
    iosClientId: '1014162331467-tknsgivba45i2151qihnu4c24tbr8kr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo2',
  );

}